#!/usr/bin/perl
# chat.cgi
# Handles AJAX requests for chatbot conversation

use strict;
use warnings;
require '../web-lib.pl';
require './aihelp-lib.pl';
our (%text, %in, %config);

&init_config();
&ReadParse();

# Get config and check for API Key
my %cfg = &get_config();
my $api_key = $cfg{'gemini_api_key'};
if (!$api_key) {
    &print_json({ 'error' => 'Gemini API Key is not configured.' });
    exit;
}

my $message = $in{'message'};
if (!defined($message)) {
    &print_json({ 'error' => 'No message parameter received.' });
    exit;
}
$message =~ s/^\s+//;
$message =~ s/\s+$//;
if (!$message) {
    &print_json({ 'error' => 'Message is empty.' });
    exit;
}

# 1. Search local Webmin help documentation (RAG)
my @docs = &search_help_index($message);

# 2. Construct prompt template
my $context_str = "";
if (@docs) {
    $context_str = "Here is some potentially relevant local Webmin documentation context:\n\n";
    foreach my $doc (@docs) {
        $context_str .= "--- Module: " . $doc->{'module'} . " (File: " . $doc->{'file'} . ") ---\n";
        $context_str .= $doc->{'text'} . "\n\n";
    }
}

my $prompt = "You are a helpful and knowledgeable AI assistant for Webmin, a web-based system administration tool for Unix/Linux.\n";
$prompt .= "Your task is to answer the user's question about Webmin or how to perform a task.\n";
if ($context_str) {
    $prompt .= "Use the following local Webmin help documentation context to help formulate your answer if it is relevant. If the context does not contain the answer, you can use your general knowledge of Webmin and Linux administration, but prioritize the provided context where applicable:\n\n";
    $prompt .= $context_str;
}
$prompt .= "User question: $message\n";
$prompt .= "Answer (use Markdown formatting, be concise, clear, and professional):";

# 3. Call Google Gemini API
my $payload = {
    'contents' => [
        {
            'parts' => [
                {
                    'text' => $prompt
                }
            ]
        }
    ]
};
my $json_payload = &convert_to_json($payload);

# Gemini API Endpoint parameters
my $host = "generativelanguage.googleapis.com";
my $port = 443;
my $page = "/v1beta/models/gemini-1.5-flash:generateContent?key=" . $api_key;
my $ssl = 1;

my $response_body = "";
my $error_msg = "";
my $headers = {
    'Content-Type' => 'application/json'
};

my $ok = &http_post($host, $port, $page, $json_payload, \$response_body, \$error_msg, undef, $ssl, undef, undef, 30, 0, 1, $headers);

if (!$ok) {
    my $err = $error_msg || "Unknown HTTP POST error.";
    &print_json({ 'error' => "HTTP POST failed: $err" });
    exit;
}

# Parse response JSON
my $resp;
eval {
    $resp = &convert_from_json($response_body);
};
if ($@ || ref($resp) ne 'HASH' || !$resp->{'candidates'}) {
    &print_json({ 'error' => 'Invalid or empty response from Gemini API.', 'raw' => $response_body });
    exit;
}

my $candidate = $resp->{'candidates'}->[0];
if (!$candidate || !$candidate->{'content'} || !$candidate->{'content'}->{'parts'}) {
    &print_json({ 'error' => 'No content candidate generated.', 'raw' => $response_body });
    exit;
}

my $reply = $candidate->{'content'}->{'parts'}->[0]->{'text'};
if (!$reply) {
    &print_json({ 'error' => 'Empty text generated by Gemini.', 'raw' => $response_body });
    exit;
}

&print_json({ 'reply' => $reply });
